/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.27
 * Generated at: 2018-02-11 11:17:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-sale=1, shrink-to-fit=no\">\n");
      out.write("  <title>Course Evaluation</title>\n");
      out.write("  <!-- bootstrap CSS -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/bootstrap.min.css\">\n");
      out.write("  <!-- custom CSS -->\n");
      out.write("  <link rel=\"stylesheet\" href=\"./css/custom.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <!-- Navbar -->\n");
      out.write("  <nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("    <a class =\"navbar-brand\" href=\"index.jsp\">Course Evaluation</a>\n");
      out.write("    <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbar\" name=\"button\">\n");
      out.write("      <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("    </button>\n");
      out.write("    <div id=\"navbar\" class=\"collapse navbar-collapse\">\n");
      out.write("      <ul class=\"navbar-nav mr-auto\">\n");
      out.write("        <li class=\"nav-item active\">\n");
      out.write("          <a class=\"nav-link\" href=\"index.jsp\">Main</a>\n");
      out.write("        </li>\n");
      out.write("        <li class=\"nav-item dropdown\">\n");
      out.write("          <a class=\"nav-link dropdown-toggle\" id=\"dropdown\" data-toggle=\"dropdown\" href=\"#\">\n");
      out.write("            Users\n");
      out.write("          </a>\n");
      out.write("          <div class=\"dropdown-menu\" aria-labelledby=\"dropdown\">\n");
      out.write("            <a class=\"dropdown-item\" href=\"userLogin.jsp\">Log in</a>\n");
      out.write("            <a class=\"dropdown-item\" href=\"userJoin.jsp\">Sign up</a>\n");
      out.write("            <a class=\"dropdown-item\" href=\"userLogout.jsp\">Log out</a>\n");
      out.write("          </div>\n");
      out.write("        </li>\n");
      out.write("      </ul>\n");
      out.write("      <form class=\"form-inline my-2 my-lg-0\">\n");
      out.write("        <input class=\"form-control mr-sm-2\" type=\"search\" placeholder=\"search\" aria-label=\"Search\">\n");
      out.write("        <button class=\"btn btn-outline-success my-2 my-sm-0\" type=\"submit\">search</button>\n");
      out.write("      </form>\n");
      out.write("    </div>\n");
      out.write("  </nav>\n");
      out.write("\n");
      out.write("  <section class=\"container\">\n");
      out.write("    <form class=\"form-inline mt-3\" action=\"./index.jsp\" method=\"get\">\n");
      out.write("      <select class=\"form-control mx-1 mt-2\" name=\"lectureDivide\">\n");
      out.write("        <option value=\"all\">All</option>\n");
      out.write("        <option value=\"major\">Major</option>\n");
      out.write("        <option value=\"elective\">Elective</option>\n");
      out.write("        <option value=\"others\">Others</option>\n");
      out.write("      </select>\n");
      out.write("      <input type=\"text\" name=\"search\" class=\"form-control mx-1 mt-2\" placeholder=\"search\">\n");
      out.write("      <button type=\"submit\" class=\"btn btn-primary mx-1 mt-2\">Search</button>\n");
      out.write("      <a class=\"btn btn-primary mx-1 mt-2\" data-toggle=\"modal\" href=\"#registerModal\">Register</a>\n");
      out.write("      <a class=\"btn btn-danger mx-1 mt-2\" data-toggle=\"modal\" href=\"#reportModal\">Report</a>\n");
      out.write("    </form>\n");
      out.write("    <div class=\"card bg-light mt-3\">\n");
      out.write("      <div class=\"card-header bg-light\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-8 text-left\">Intro to Computer Science &nbsp; <small>Mijeong Ban</small></div>\n");
      out.write("          <div class=\"col-4 text-right\">\n");
      out.write("            Overall <span style=\"color: red;\">A</span>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card-body\">\n");
      out.write("        <h5 class=\"card-title\">\n");
      out.write("          Best course!&nbsp;<small>(Fall 2017)</small>\n");
      out.write("        </h5>\n");
      out.write("        <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-9 text-left\">\n");
      out.write("            Grade <span style=\"color: red;\">A</span>\n");
      out.write("            Difficulty <span style=\"color: red;\">A</span>\n");
      out.write("            Hotness <span style=\"color: red;\">A</span>\n");
      out.write("            <span style=\"color: green;\">(recommend: 15)</span>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-3 text-right\">\n");
      out.write("            <a onclick=\"return conficm('recommend?')\" href=\"./likeAction.jsp?evaluationID\">Recommend</a>\n");
      out.write("            <a onclick=\"return confirm('delete?')\" href=\"./deleteAction.jsp?evaluationID\">Delete</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"card bg-light mt-3\">\n");
      out.write("      <div class=\"card-header bg-light\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-8 text-left\">Data Structures &nbsp; <small>Mijeong Ban</small></div>\n");
      out.write("          <div class=\"col-4 text-right\">\n");
      out.write("            Overall <span style=\"color: red;\">A</span>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card-body\">\n");
      out.write("        <h5 class=\"card-title\">\n");
      out.write("          Best course!&nbsp;<small>(Fall 2016)</small>\n");
      out.write("        </h5>\n");
      out.write("        <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-9 text-left\">\n");
      out.write("            Grade <span style=\"color: red;\">A</span>\n");
      out.write("            Difficulty <span style=\"color: red;\">A</span>\n");
      out.write("            Hotness <span style=\"color: red;\">A</span>\n");
      out.write("            <span style=\"color: green;\">(recommend: 2)</span>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-3 text-right\">\n");
      out.write("            <a onclick=\"return conficm('recommend?')\" href=\"./likeAction.jsp?evaluationID\">Recommend</a>\n");
      out.write("            <a onclick=\"return confirm('delete?')\" href=\"./deleteAction.jsp?evaluationID\">Delete</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"card bg-light mt-3\">\n");
      out.write("      <div class=\"card-header bg-light\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-8 text-left\">Algorithms &nbsp; <small>Mijeong Ban</small></div>\n");
      out.write("          <div class=\"col-4 text-right\">\n");
      out.write("            Overall <span style=\"color: red;\">A</span>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"card-body\">\n");
      out.write("        <h5 class=\"card-title\">\n");
      out.write("          Best course!&nbsp;<small>(Spring 2017)</small>\n");
      out.write("        </h5>\n");
      out.write("        <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>\n");
      out.write("        <div class=\"row\">\n");
      out.write("          <div class=\"col-9 text-left\">\n");
      out.write("            Grade <span style=\"color: red;\">A</span>\n");
      out.write("            Difficulty <span style=\"color: red;\">A</span>\n");
      out.write("            Hotness <span style=\"color: red;\">A</span>\n");
      out.write("            <span style=\"color: green;\">(recommend: 3)</span>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"col-3 text-right\">\n");
      out.write("            <a onclick=\"return conficm('recommend?')\" href=\"./likeAction.jsp?evaluationID\">Recommend</a>\n");
      out.write("            <a onclick=\"return confirm('delete?')\" href=\"./deleteAction.jsp?evaluationID\">Delete</a>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  </section>\n");
      out.write("  <div class=\"modal fade\" id=\"registerModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog\">\n");
      out.write("          <div class=\"modal-content\">\n");
      out.write("            <div class=\"modal-header\">\n");
      out.write("              <h4 class=\"modal-title\" id=\"modal\">Register Evaluation</h4>\n");
      out.write("              <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("                <span aria-hidden=\"true\">&times;</span>\n");
      out.write("              </button>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"modal-body\">\n");
      out.write("              <form action=\"./evaluationRegisterAction.jsp\" method=\"post\">\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                  <div class=\"form-group col-sm-6\">\n");
      out.write("                    <label>Course Title</label>\n");
      out.write("                    <input type=\"text\" name=\"courseName\" class=\"form-control\" maxlength=\"20\">\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group col-sm-6\">\n");
      out.write("                    <label>Professor</label>\n");
      out.write("                    <input type=\"text\" name=\"professorName\" class=\"form-control\" maxlength=\"20\">\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                  <div class=\"form-group col-sm-4\">\n");
      out.write("                    <label>Year</label>\n");
      out.write("                    <select name=\"lectureYear\" class=\"form-control\">\n");
      out.write("                      <option value=\"2011\">2011</option>\n");
      out.write("                      <option value=\"2012\">2012</option>\n");
      out.write("                      <option value=\"2013\">2013</option>\n");
      out.write("                      <option value=\"2014\">2014</option>\n");
      out.write("                      <option value=\"2015\">2015</option>\n");
      out.write("                      <option value=\"2016\">2016</option>\n");
      out.write("                      <option value=\"2017\">2017</option>\n");
      out.write("                      <option value=\"2018\" selected>2018</option>\n");
      out.write("                      <option value=\"2019\">2019</option>\n");
      out.write("                      <option value=\"2020\">2020</option>\n");
      out.write("                      <option value=\"2021\">2021</option>\n");
      out.write("                      <option value=\"2022\">2022</option>\n");
      out.write("                      <option value=\"2023\">2023</option>\n");
      out.write("                    </select>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group col-sm-4\">\n");
      out.write("                    <label>Semester</label>\n");
      out.write("                    <select name=\"semesterDivide\" class=\"form-control\">\n");
      out.write("                      <option value=\"fall\">Fall</option>\n");
      out.write("                      <option value=\"winter\">Winter Session</option>\n");
      out.write("                      <option value=\"spring\">Spring</option>\n");
      out.write("                      <option value=\"summer1\">Summer I</option>\n");
      out.write("                      <option value=\"summer2\">Summer II</option>\n");
      out.write("                    </select>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group col-sm-4\">\n");
      out.write("                    <label>Division</label>\n");
      out.write("                    <select name=\"lectureDivide\" class=\"form-control\">\n");
      out.write("                      <option value=\"core\" selected>Core</option>\n");
      out.write("                      <option value=\"elective\">Electives</option>\n");
      out.write("                      <option value=\"others\">Others</option>\n");
      out.write("                    </select>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <label>Title</label>\n");
      out.write("                  <input type=\"text\" name=\"evaluationTitle\" class=\"form-control\" maxlength=\"20\">\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-group\">\n");
      out.write("                  <label>Contents</label>\n");
      out.write("                  <textarea name=\"evaluationContent\" class=\"form-control\" maxlength=\"2048\" style=\"height: 180px;\"></textarea>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"form-row\">\n");
      out.write("                  <div class=\"form-group col-sm-3\">\n");
      out.write("                    <label>Overall Quality</label>\n");
      out.write("                    <select name=\"overall\" class=\"form-control\">\n");
      out.write("                      <option value=\"A\" selected>A</option>\n");
      out.write("                      <option value=\"B\">B</option>\n");
      out.write("                      <option value=\"C\">C</option>\n");
      out.write("                      <option value=\"D\">D</option>\n");
      out.write("                      <option value=\"F\">F</option>\n");
      out.write("                    </select>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group col-sm-3\">\n");
      out.write("                    <label>Grade</label>\n");
      out.write("                    <select name=\"grade\" class=\"form-control\">\n");
      out.write("                      <option value=\"A\" selected>A</option>\n");
      out.write("                      <option value=\"B\">B</option>\n");
      out.write("                      <option value=\"C\">C</option>\n");
      out.write("                      <option value=\"D\">D</option>\n");
      out.write("                      <option value=\"F\">F</option>\n");
      out.write("                    </select>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group col-sm-3\">\n");
      out.write("                    <label>Difficulty</label>\n");
      out.write("                    <select name=\"difficulty\" class=\"form-control\">\n");
      out.write("                      <option value=\"A\" selected>A</option>\n");
      out.write("                      <option value=\"B\">B</option>\n");
      out.write("                      <option value=\"C\">C</option>\n");
      out.write("                      <option value=\"D\">D</option>\n");
      out.write("                      <option value=\"F\">F</option>\n");
      out.write("                    </select>\n");
      out.write("                  </div>\n");
      out.write("                  <div class=\"form-group col-sm-3\">\n");
      out.write("                    <label>Hotness</label>\n");
      out.write("                    <select name=\"hotness\" class=\"form-control\">\n");
      out.write("                      <option value=\"A\" selected>A</option>\n");
      out.write("                      <option value=\"B\">B</option>\n");
      out.write("                      <option value=\"C\">C</option>\n");
      out.write("                      <option value=\"D\">D</option>\n");
      out.write("                      <option value=\"F\">F</option>\n");
      out.write("                    </select>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("                <div class=\"modal-footer\">\n");
      out.write("                  <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Cancel</button>\n");
      out.write("                  <button type=\"submit\" class=\"btn btn-primary\">Register</button>\n");
      out.write("                </div>\n");
      out.write("              </form>\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"modal fade\" id=\"reportModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"modal\" aria-hidden=\"true\">\n");
      out.write("      <div class=\"modal-dialog\">\n");
      out.write("        <div class=\"modal-content\">\n");
      out.write("          <div class=\"modal-header\">\n");
      out.write("            <h4 class=\"modal-title\" id=\"modal\">Report</h4>\n");
      out.write("            <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("              <span aria-hidden=\"true\">&times;</span>\n");
      out.write("            </button>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"modal-body\">\n");
      out.write("            <form method=\"post\" action=\"./reportAction.jsp\">\n");
      out.write("              <div class=\"form-group\">\n");
      out.write("                <label>Report Title</label>\n");
      out.write("                <input type=\"text\" name=\"reportTitle\" class=\"form-control\" maxlength=\"20\">\n");
      out.write("              </div>\n");
      out.write("              <div class=\"form-group\">\n");
      out.write("                <label>Report Contents</label>\n");
      out.write("                <textarea name=\"reportContent\" class=\"form-control\" maxlength=\"2048\" style=\"height: 180px;\"></textarea>\n");
      out.write("              </div>\n");
      out.write("              <div class=\"modal-footer\">\n");
      out.write("                <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Cancel</button>\n");
      out.write("                <button type=\"submit\" class=\"btn btn-danger\">Report</button>\n");
      out.write("              </div>\n");
      out.write("            </form>\n");
      out.write("          </div>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("    </div>\n");
      out.write("  <footer class=\"bg-dark mt-4 p-5 text-center\" style=\"color: #FFFFFF;\">\n");
      out.write("      Copyright ⓒ 2018 halfundecided All Rights Reserved.\n");
      out.write("  </footer>\n");
      out.write("  <!-- jQuery javaScript -->\n");
      out.write("  <script type=\"text/javascript\" src=\"./js/jquery.min.js\"></script>\n");
      out.write("  <!-- popper -->\n");
      out.write("  <script type=\"text/javascript\" src=\"./js/popper.min.js\"></script>\n");
      out.write("  <!-- bootstrap javaScript -->\n");
      out.write("  <script type=\"text/javascript\" src=\"./js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
